site_name: Tathagata Mukherjee

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js


nav:
  - Section:
    - Home: index.md
    - About Me: aboutMe.md 
    - Contact Info: contactInfo.md
    - Education: education.md
    - Research: research.md
    - News & Media Coverage: news.md
    - Academic Memberships: academicMemberships.md
    - Teaching: teaching.md
    - Hosted Post Doctoral Fellowships: hostedPostDoc.md
    - Graduated Doctoral Students: graduatedPhD.md
    - Graduated Master's Thesis Students: graduatedMastersThesis.md
    - Current Students: currentStudents.md
    - Mentoring and Committees of Students: mentoring.md
    - Service: service.md

hide:
  - navigation
  - toc


theme:
  palette:
    primary: teal
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  icon:
    # logo: bootstrap/eye
  features:
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

# plugins:
#   - social
